### ISSUE TITLE
Compilation Error CS0246

### ISSUE THREAD

**Issue by mohammadyou** [psenechal/PJS.Envision#3]
Hi. 
Having said in the instruction of the theme I cloned it in the theme folder and in the admin of the site I checked the "set current" but unfortunately I get this error:

Compiler Error Message: CS0246: The type or namespace name 'PJS' could not be found (are you missing a using directive or an assembly reference?)

Source Error:
Line 1:  @using Orchard.ContentManagement;
Line 2:  @using PJS.Envision.Models;
Line 3:  
Line 4:  @functions {
Source File: W:\Project\ERP\Orchard\src\Orchard.Web\Themes\PJS.Envision\Views\Layout.cshtml    Line: 2 

Am I missing something ? 
Thanks

**Comment by psenechal** [comment]
Try rebuilding the project in Visual Studio

**Comment by mohammadyou** [comment]
cheers mate

**Comment by psenechal** [comment]
No worries...this happens a lot to me when I pull new themes with a lot of code.
